import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "ProVest",
  description: "Generated by JENGT",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        {/* Ícone para o navegador */}
        <link rel="icon" href="/img/iconProvest.png" />
        {/* Ícone para dispositivos móveis */}
        <link rel="apple-touch-icon" href="/img/iconProvest.png" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <div id="modal-root" className=""></div>
      </body>
    </html>
  );
}